export const USER_SIGNIN_REQUIST='USER_SIGNIN_REQUIST';
export const USER_SIGNIN_SUCCESS='USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAILED='USER_SIGNIN_FAILED';

export const USER_REGISTER_REQUIST='USER_REGISTER_REQUIST';
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED='USER_REGISTERS_FAILED';